# First steps with Polars
## Requisitos de Docker antes de instalar.
ocker destaca por su compatibilidad entre sistemas. Las máquinas virtuales o la virtualización de hardware clásica emulan un sistema operativo invitado entero, mientras que los contenedores Docker comparten el núcleo del sistema anfitrión, ejecutándose como procesos aislados en el espacio del usuario. En sus inicios, Docker se utilizaba exclusivamente en sistemas Linux o en sistemas operativos basados en Linux. Hoy en día, el software de código abierto se caracteriza por su completa independencia de los sistemas operativos. Docker utiliza el kernel local de Linux en las variantes de 64 bits de los sistemas operativos de Linux, los sistemas que no son de Linux utilizan simplemente una imagen del sistema Linux a través de un hypervisor o una máquina virtual.

# Las distribuciones de Linux compatibles son las siguientes:

* Fedora
* Ubuntu
* CentOS
* Oracle Linux
* Red Hat Enterprise Linux
* openSUSE
* SUSE Linux Enterprise

La página oficial de Docker ofrece los paquetes de instalación correspondientes tanto para Windows y macOS, como para los servicios en la nube como Azure o AWS.